/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KimiCanvasPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/kimi-bridge.ts
var import_child_process = require("child_process");
var import_events = require("events");
var KimiBridge = class extends import_events.EventEmitter {
  cp;
  cwd;
  kimiPath;
  buffer = "";
  requestId = 0;
  pendingRequestIds = /* @__PURE__ */ new Set();
  state = "idle";
  sessionId;
  messageAccumulator = "";
  get currentState() {
    return this.state;
  }
  get activeSessionId() {
    return this.sessionId;
  }
  constructor(cwd, kimiPath = "kimi") {
    super();
    this.cwd = cwd;
    this.kimiPath = kimiPath;
  }
  connect() {
    if (this.cp || this.state !== "idle")
      return;
    this.state = "connecting";
    this.sessionId = void 0;
    this.requestId = 0;
    this.pendingRequestIds.clear();
    this.messageAccumulator = "";
    try {
      this.cp = (0, import_child_process.spawn)(this.kimiPath, ["acp"], {
        cwd: this.cwd,
        env: process.env,
        stdio: ["pipe", "pipe", "pipe"]
      });
    } catch (e) {
      this.state = "idle";
      const msg = e?.code === "ENOENT" ? `Cannot find kimi executable at "${this.kimiPath}". Please set the correct path in Kimi Canvas settings.` : `Failed to spawn kimi acp: ${e?.message ?? e}`;
      this.emit("error", msg);
      return;
    }
    this.cp.stdout?.on("data", (chunk) => {
      this.buffer += chunk.toString("utf-8");
      this.processBuffer();
    });
    this.cp.stderr?.on("data", (chunk) => {
      const text = chunk.toString("utf-8").trim();
      if (text)
        this.emit("stderr", text);
    });
    this.cp.on("exit", (code) => {
      const wasReady = this.state === "ready" || this.state === "prompting";
      this.cp = void 0;
      this.state = "idle";
      this.sessionId = void 0;
      if (wasReady) {
        this.emit("disconnected", code);
      } else {
        this.emit("error", `kimi acp exited unexpectedly (code ${code ?? "unknown"})`);
      }
    });
    this.cp.on("error", (err) => {
      const msg = err?.code === "ENOENT" ? `Cannot find kimi executable at "${this.kimiPath}". Please set the correct path in Kimi Canvas settings.` : `kimi acp process error: ${err.message}`;
      this.emit("error", msg);
      if (this.state !== "idle") {
        this.state = "idle";
        this.cp = void 0;
      }
    });
    this.sendRequest("initialize", {
      protocolVersion: 1,
      clientCapabilities: {},
      clientInfo: { name: "obsidian-kimi-canvas", version: "0.3.0" }
    });
    this.state = "initializing";
  }
  disconnect() {
    this.cp?.kill();
    this.cp = void 0;
    this.state = "idle";
    this.sessionId = void 0;
    this.pendingRequestIds.clear();
  }
  reconnect() {
    this.disconnect();
    this.connect();
  }
  sendRequest(method, params) {
    const id = ++this.requestId;
    const line = JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n";
    this.pendingRequestIds.add(id);
    this.cp?.stdin?.write(line);
    return id;
  }
  sendNotification(method, params) {
    const line = JSON.stringify({ jsonrpc: "2.0", method, params }) + "\n";
    this.cp?.stdin?.write(line);
  }
  sendPrompt(text, images) {
    if (this.state !== "ready" || !this.sessionId) {
      this.emit("error", "Kimi ACP is not ready. Please wait for connection or reconnect.");
      return;
    }
    this.messageAccumulator = "";
    const prompt = [];
    if (text.trim()) {
      prompt.push({ type: "text", text });
    }
    if (images && images.length > 0) {
      for (const img of images) {
        prompt.push({ type: "image", data: img.data, mimeType: img.mimeType });
      }
    }
    if (prompt.length === 0) {
      this.emit("error", "Cannot send empty prompt.");
      return;
    }
    this.sendRequest("session/prompt", {
      sessionId: this.sessionId,
      prompt
    });
    this.state = "prompting";
    this.emit("promptStarted");
  }
  processBuffer() {
    const lines = this.buffer.split("\n");
    this.buffer = lines.pop() ?? "";
    for (const line of lines) {
      if (!line.trim())
        continue;
      try {
        const msg = JSON.parse(line);
        this.handleMessage(msg);
      } catch (e) {
      }
    }
  }
  handleMessage(msg) {
    if (msg.method && msg.params !== void 0) {
      this.handleNotification(msg.method, msg.params);
      return;
    }
    if (msg.id !== void 0) {
      this.pendingRequestIds.delete(msg.id);
      if (msg.error) {
        this.handleErrorResponse(msg.error);
        return;
      }
      this.handleSuccessResponse(msg.id, msg.result);
    }
  }
  handleNotification(method, params) {
    if (method === "session/update") {
      const update = params?.update;
      if (!update)
        return;
      switch (update.sessionUpdate) {
        case "agent_thought_chunk":
        case "agent_message_chunk": {
          const text = update.content?.text ?? "";
          if (update.sessionUpdate === "agent_message_chunk") {
            this.messageAccumulator += text;
            this.emit("chunk", { type: "message", text });
          } else {
            this.emit("chunk", { type: "thought", text });
          }
          break;
        }
        case "tool_call_update": {
          this.emit("toolCall", update);
          break;
        }
        case "available_commands_update":
        case "current_mode_update":
        case "usage_update":
        case "plan":
        case "config_option_update":
        case "session_info_update": {
          this.emit("notification", { method, params });
          break;
        }
        default:
          this.emit("notification", { method, params });
          break;
      }
    } else {
      this.emit("notification", { method, params });
    }
  }
  handleSuccessResponse(id, result) {
    if (this.state === "initializing") {
      this.sendRequest("session/new", {
        cwd: this.cwd,
        mcpServers: []
      });
      this.state = "creating_session";
      return;
    }
    if (this.state === "creating_session") {
      this.sessionId = result?.sessionId;
      if (this.sessionId) {
        this.state = "ready";
        this.emit("connected", { sessionId: this.sessionId });
      } else {
        this.state = "idle";
        this.emit("error", "ACP session/new did not return a sessionId");
      }
      return;
    }
    if (this.state === "prompting") {
      this.state = "ready";
      const stopReason = result?.stopReason ?? "unknown";
      this.emit("promptDone", { stopReason, fullText: this.messageAccumulator });
      return;
    }
  }
  handleErrorResponse(error) {
    const code = error?.code;
    const message = error?.message ?? "Unknown ACP error";
    if (code === -32e3) {
      this.emit("authRequired", message);
      this.disconnect();
      return;
    }
    if (this.state === "initializing" || this.state === "creating_session") {
      this.state = "idle";
    }
    if (this.state === "prompting") {
      this.state = "ready";
    }
    this.emit("error", `ACP error [${code}]: ${message}`);
  }
  clearSession() {
    this.sessionId = void 0;
    this.messageAccumulator = "";
    if (this.state === "ready" || this.state === "prompting") {
      this.disconnect();
      this.connect();
    }
  }
  // Legacy fallback helpers (keep compatibility with quiet mode code if needed)
  async runQuiet(_prompt, _extraArgs = []) {
    throw new Error("Quiet mode is deprecated in ACP bridge.");
  }
  async runQuietWithContext(_system, _history, _user) {
    throw new Error("Quiet mode is deprecated in ACP bridge.");
  }
};

// src/canvas-manager.ts
var DEFAULT_NODE_WIDTH = 260;
var DEFAULT_NODE_HEIGHT = 140;
var LEVEL_GAP_X = 320;
var LEVEL_GAP_Y = 200;
var CanvasManager = class {
  vault;
  constructor(vault) {
    this.vault = vault;
  }
  async readCanvas(file) {
    const content = await this.vault.read(file);
    try {
      return JSON.parse(content);
    } catch (e) {
      return { nodes: [], edges: [] };
    }
  }
  async writeCanvas(file, data) {
    const content = JSON.stringify(data, null, "	");
    await this.vault.modify(file, content);
  }
  ensureCanvasData(data) {
    return {
      nodes: data.nodes ?? [],
      edges: data.edges ?? []
    };
  }
  // Apply a partial update (from AI) onto existing canvas
  applyCanvasUpdate(base, update) {
    const result = {
      nodes: [...base.nodes ?? []],
      edges: [...base.edges ?? []]
    };
    if (update.nodes) {
      for (const n of update.nodes) {
        const idx = result.nodes.findIndex((x) => x.id === n.id);
        if (idx >= 0) {
          result.nodes[idx] = { ...result.nodes[idx], ...n };
        } else {
          result.nodes.push({
            ...n,
            width: n.width ?? DEFAULT_NODE_WIDTH,
            height: n.height ?? DEFAULT_NODE_HEIGHT
          });
        }
      }
    }
    if (update.edges) {
      for (const e of update.edges) {
        const idx = result.edges.findIndex((x) => x.id === e.id);
        if (idx >= 0) {
          result.edges[idx] = { ...result.edges[idx], ...e };
        } else {
          result.edges.push(e);
        }
      }
    }
    return result;
  }
  // Simple hierarchical tree layout (left-to-right)
  autoLayout(data, options) {
    const { nodes, edges } = this.ensureCanvasData(data);
    if (nodes.length === 0)
      return data;
    const direction = options?.direction ?? "lr";
    const outgoing = /* @__PURE__ */ new Map();
    const incoming = /* @__PURE__ */ new Map();
    for (const n of nodes) {
      outgoing.set(n.id, []);
      incoming.set(n.id, []);
    }
    for (const e of edges) {
      if (outgoing.has(e.fromNode) && incoming.has(e.toNode)) {
        outgoing.get(e.fromNode).push(e.toNode);
        incoming.get(e.toNode).push(e.fromNode);
      }
    }
    const levels = /* @__PURE__ */ new Map();
    const visited = /* @__PURE__ */ new Set();
    const dfs = (id, depth) => {
      const prev = levels.get(id) ?? 0;
      levels.set(id, Math.max(prev, depth));
      if (visited.has(id))
        return;
      visited.add(id);
      for (const child of outgoing.get(id) ?? []) {
        dfs(child, depth + 1);
      }
    };
    const roots = nodes.filter((n) => (incoming.get(n.id) ?? []).length === 0).map((n) => n.id);
    if (roots.length === 0 && nodes.length > 0) {
      roots.push(nodes[0].id);
    }
    for (const r of roots)
      dfs(r, 0);
    const levelGroups = /* @__PURE__ */ new Map();
    for (const [id, lvl] of levels) {
      if (!levelGroups.has(lvl))
        levelGroups.set(lvl, []);
      levelGroups.get(lvl).push(id);
    }
    const newNodes = nodes.map((n) => ({ ...n }));
    for (const node of newNodes) {
      const lvl = levels.get(node.id) ?? 0;
      const group = levelGroups.get(lvl);
      const idx = group.indexOf(node.id);
      if (direction === "lr") {
        node.x = lvl * LEVEL_GAP_X + 40;
        node.y = idx * LEVEL_GAP_Y + 40;
      } else {
        node.x = idx * LEVEL_GAP_X + 40;
        node.y = lvl * LEVEL_GAP_Y + 40;
      }
    }
    return { nodes: newNodes, edges };
  }
  // Extract canvas operation block from AI response
  parseCanvasOpBlock(text) {
    const marker = "// kimi-canvas-op";
    const idx = text.indexOf(marker);
    if (idx < 0)
      return null;
    const after = text.slice(idx + marker.length);
    const match = after.match(/```json\s*([\s\S]*?)```/);
    if (!match)
      return null;
    try {
      return JSON.parse(match[1].trim());
    } catch (e) {
      return null;
    }
  }
  // Clean the visible text by removing the operation block
  stripCanvasOpBlock(text) {
    const marker = "// kimi-canvas-op";
    const idx = text.indexOf(marker);
    if (idx < 0)
      return text;
    return text.slice(0, idx).trim();
  }
  generateId() {
    return Math.random().toString(36).substring(2, 10);
  }
};

// src/chat-view.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_KIMI_CHAT = "kimi-canvas-chat";
var KimiChatView = class extends import_obsidian.ItemView {
  plugin;
  messages = [];
  messageContainer;
  inputEl;
  sendBtn;
  statusEl;
  isProcessing = false;
  // Streaming state
  currentAssistantBubble;
  currentAssistantContent;
  currentAssistantThinking;
  currentAssistantText = "";
  currentThinkingText = "";
  // Pending images for next prompt
  pendingImages = [];
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.bindBridgeEvents();
  }
  getViewType() {
    return VIEW_TYPE_KIMI_CHAT;
  }
  getDisplayText() {
    return "Kimi Canvas";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("kimi-canvas-container");
    const header = contentEl.createEl("div", { cls: "kimi-canvas-header" });
    header.createEl("span", { text: "Kimi Canvas", cls: "kimi-canvas-title" });
    const controls = header.createEl("span", { cls: "kimi-canvas-header-controls" });
    const screenshotBtn = controls.createEl("button", { cls: "kimi-canvas-header-btn", attr: { "aria-label": "Capture canvas screenshot" } });
    (0, import_obsidian.setIcon)(screenshotBtn, "camera");
    screenshotBtn.addEventListener("click", () => this.triggerManualScreenshot());
    const reconnectBtn = controls.createEl("button", { cls: "kimi-canvas-header-btn", attr: { "aria-label": "Reconnect ACP" } });
    (0, import_obsidian.setIcon)(reconnectBtn, "refresh-cw");
    reconnectBtn.addEventListener("click", () => {
      this.appendSystemMessage("Reconnecting to Kimi ACP...");
      this.plugin.kimi.reconnect();
    });
    const clearBtn = controls.createEl("button", { cls: "kimi-canvas-header-btn", attr: { "aria-label": "Clear chat" } });
    (0, import_obsidian.setIcon)(clearBtn, "trash-2");
    clearBtn.addEventListener("click", () => this.clearChat());
    this.statusEl = contentEl.createEl("div", { cls: "kimi-canvas-status" });
    this.updateStatus("disconnected");
    this.messageContainer = contentEl.createEl("div", { cls: "kimi-canvas-messages" });
    const inputArea = contentEl.createEl("div", { cls: "kimi-canvas-input-area" });
    const fileInput = inputArea.createEl("input", {
      cls: "kimi-file-input",
      attr: { type: "file", accept: "image/*", multiple: "true" }
    });
    fileInput.addEventListener("change", (evt) => this.onFileSelected(evt));
    const attachBtn = inputArea.createEl("button", { cls: "kimi-canvas-attach-btn", attr: { "aria-label": "Attach image" } });
    (0, import_obsidian.setIcon)(attachBtn, "paperclip");
    attachBtn.addEventListener("click", () => fileInput.click());
    this.inputEl = inputArea.createEl("textarea", { cls: "kimi-canvas-input" });
    this.inputEl.placeholder = "Ask Kimi about your canvas, or type a command...";
    this.inputEl.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter" && !evt.shiftKey) {
        evt.preventDefault();
        this.sendMessage();
      }
    });
    this.sendBtn = inputArea.createEl("button", { cls: "kimi-canvas-send-btn" });
    (0, import_obsidian.setIcon)(this.sendBtn, "send");
    this.sendBtn.addEventListener("click", () => this.sendMessage());
    this.addWelcomeMessage();
    if (this.plugin.kimi.currentState === "idle") {
      this.plugin.kimi.connect();
    } else {
      this.updateStatus(this.plugin.kimi.currentState);
    }
  }
  bindBridgeEvents() {
    const bridge = this.plugin.kimi;
    bridge.on("connected", () => this.updateStatus("ready"));
    bridge.on("disconnected", () => this.updateStatus("disconnected"));
    bridge.on("error", (msg) => {
      this.updateStatus("error");
      this.appendSystemMessage(`Error: ${msg}`);
      this.setProcessing(false);
    });
    bridge.on("authRequired", (msg) => {
      this.updateStatus("auth");
      this.appendSystemMessage(`Auth required: ${msg}
Please run "kimi login" in your terminal first.`);
      this.setProcessing(false);
    });
    bridge.on("promptStarted", () => {
      this.beginAssistantStream();
    });
    bridge.on("chunk", (chunk) => {
      this.onStreamChunk(chunk);
    });
    bridge.on("promptDone", async (info) => {
      await this.onStreamDone(info);
    });
  }
  updateStatus(state) {
    if (!this.statusEl)
      return;
    const map = {
      idle: { text: "Idle", cls: "kimi-status-idle" },
      connecting: { text: "Connecting...", cls: "kimi-status-connecting" },
      initializing: { text: "Initializing...", cls: "kimi-status-connecting" },
      creating_session: { text: "Creating session...", cls: "kimi-status-connecting" },
      ready: { text: "Ready", cls: "kimi-status-ready" },
      prompting: { text: "Thinking...", cls: "kimi-status-prompting" },
      disconnected: { text: "Disconnected", cls: "kimi-status-disconnected" },
      error: { text: "Error", cls: "kimi-status-error" },
      auth: { text: "Auth Required", cls: "kimi-status-error" }
    };
    const s = map[state] ?? { text: state, cls: "" };
    this.statusEl.textContent = s.text;
    this.statusEl.className = `kimi-canvas-status ${s.cls}`;
  }
  addWelcomeMessage() {
    this.appendSystemMessage(
      "Welcome! I can help you organize and generate Canvas boards.\n- Open a .canvas file, then chat here.\n- I can create nodes, connect ideas, and auto-layout your board.\n- You can attach screenshots (\u{1F4CE}) or let Kimi request a screen capture.\n- Make sure you have run `kimi login` in terminal."
    );
  }
  appendUserMessage(text, imagePreviews) {
    this.messages.push({ role: "user", content: text, ts: Date.now() });
    this.renderStaticMessage("user", text, imagePreviews);
  }
  appendSystemMessage(text) {
    this.renderStaticMessage("system", text);
  }
  renderStaticMessage(role, text, imagePreviews) {
    if (!this.messageContainer)
      return;
    const row = this.messageContainer.createEl("div", { cls: `kimi-msg-row kimi-msg-${role}` });
    const bubble = row.createEl("div", { cls: "kimi-msg-bubble" });
    if (imagePreviews && imagePreviews.length > 0) {
      const imgContainer = bubble.createEl("div", { cls: "kimi-msg-images" });
      for (const src of imagePreviews) {
        imgContainer.createEl("img", { cls: "kimi-msg-thumb", attr: { src } });
      }
    }
    bubble.createEl("div", { cls: "kimi-msg-content" }).innerHTML = this.markdownToHtml(text);
    this.scrollToBottom();
  }
  beginAssistantStream() {
    this.currentAssistantText = "";
    this.currentThinkingText = "";
    if (!this.messageContainer)
      return;
    const row = this.messageContainer.createEl("div", { cls: "kimi-msg-row kimi-msg-assistant" });
    const bubble = row.createEl("div", { cls: "kimi-msg-bubble" });
    this.currentAssistantThinking = bubble.createEl("div", { cls: "kimi-msg-thinking" });
    this.currentAssistantThinking.style.display = "none";
    this.currentAssistantContent = bubble.createEl("div", { cls: "kimi-msg-content" });
    this.currentAssistantContent.innerHTML = "";
    this.currentAssistantBubble = bubble;
    this.scrollToBottom();
  }
  onStreamChunk(chunk) {
    if (chunk.type === "thought") {
      this.currentThinkingText += chunk.text;
      if (this.currentAssistantThinking) {
        this.currentAssistantThinking.style.display = "block";
        this.currentAssistantThinking.textContent = this.currentThinkingText;
      }
    } else {
      this.currentAssistantText += chunk.text;
      if (this.currentAssistantContent) {
        this.currentAssistantContent.innerHTML = this.markdownToHtml(this.currentAssistantText);
      }
    }
    this.scrollToBottom();
  }
  async onStreamDone(info) {
    if (this.currentAssistantThinking) {
      this.currentAssistantThinking.style.display = "none";
    }
    let displayText = info.fullText;
    const activeCanvas = this.getActiveCanvasFile();
    let canvasApplied = false;
    if (displayText.includes("// kimi-action: screenshot")) {
      if (this.plugin.settings.autoScreenshotOnLayoutRequest) {
        this.setProcessing(false);
        this.updateStatus(this.plugin.kimi.currentState);
        await this.handleScreenshotAction();
        return;
      }
    }
    if (activeCanvas) {
      const op = this.plugin.canvasManager.parseCanvasOpBlock(displayText);
      if (op) {
        const current = await this.plugin.canvasManager.readCanvas(activeCanvas);
        let updated = this.plugin.canvasManager.applyCanvasUpdate(current, op);
        if (this.plugin.settings.autoLayoutOnUpdate) {
          updated = this.plugin.canvasManager.autoLayout(updated, {
            direction: this.plugin.settings.defaultLayoutDirection
          });
        }
        await this.plugin.canvasManager.writeCanvas(activeCanvas, updated);
        displayText = this.plugin.canvasManager.stripCanvasOpBlock(displayText);
        canvasApplied = true;
      }
    }
    if (this.currentAssistantContent) {
      this.currentAssistantContent.innerHTML = this.markdownToHtml(displayText);
    }
    if (canvasApplied && this.currentAssistantBubble) {
      this.currentAssistantBubble.createEl("div", {
        cls: "kimi-msg-meta",
        text: "\u2713 Canvas updated and auto-layout applied."
      });
    }
    this.messages.push({ role: "assistant", content: displayText, ts: Date.now() });
    this.currentAssistantBubble = void 0;
    this.currentAssistantContent = void 0;
    this.currentAssistantThinking = void 0;
    this.setProcessing(false);
    this.updateStatus(this.plugin.kimi.currentState);
  }
  setProcessing(processing) {
    this.isProcessing = processing;
    if (this.sendBtn) {
      this.sendBtn.disabled = processing;
      this.sendBtn.toggleClass("kimi-spin", processing);
    }
    if (this.inputEl) {
      this.inputEl.disabled = processing;
    }
  }
  async sendMessage() {
    if (!this.inputEl)
      return;
    const text = this.inputEl.value.trim();
    if (!text && this.pendingImages.length === 0 || this.isProcessing)
      return;
    if (this.plugin.kimi.currentState !== "ready") {
      this.appendSystemMessage("Kimi ACP is not ready yet. Please wait a moment or click the reconnect button.");
      return;
    }
    const imagesToSend = [...this.pendingImages];
    this.pendingImages = [];
    this.clearPendingImagePreview();
    this.inputEl.value = "";
    const imagePreviews = imagesToSend.map((img) => `data:${img.mimeType};base64,${img.data}`);
    this.appendUserMessage(text || "(image)", imagePreviews);
    this.setProcessing(true);
    this.updateStatus("prompting");
    const activeCanvas = this.getActiveCanvasFile();
    let canvasData;
    if (activeCanvas) {
      canvasData = await this.plugin.canvasManager.readCanvas(activeCanvas);
    }
    const system = this.buildSystemPrompt(canvasData, activeCanvas?.path, imagesToSend.length > 0);
    const fullPrompt = `${system}

--- User Request ---
${text}`;
    this.plugin.kimi.sendPrompt(fullPrompt, imagesToSend);
  }
  onFileSelected(evt) {
    const input = evt.target;
    const files = input.files;
    if (!files || files.length === 0)
      return;
    for (const file of Array.from(files)) {
      if (!file.type.startsWith("image/"))
        continue;
      const reader = new FileReader();
      reader.onload = (e) => {
        const result = e.target?.result;
        if (!result)
          return;
        const base64 = result.split(",")[1];
        this.pendingImages.push({ mimeType: file.type, data: base64 });
        this.updatePendingImagePreview();
      };
      reader.readAsDataURL(file);
    }
    input.value = "";
  }
  updatePendingImagePreview() {
    if (this.inputEl) {
      const count = this.pendingImages.length;
      this.inputEl.placeholder = count > 0 ? `${count} image(s) attached. Type a message...` : "Ask Kimi about your canvas, or type a command...";
    }
  }
  clearPendingImagePreview() {
    if (this.inputEl) {
      this.inputEl.placeholder = "Ask Kimi about your canvas, or type a command...";
    }
  }
  async triggerManualScreenshot() {
    if (this.isProcessing)
      return;
    this.appendSystemMessage("Capturing screenshot...");
    const image = await this.captureScreen();
    if (!image) {
      this.appendSystemMessage("Failed to capture screenshot.");
      return;
    }
    this.pendingImages.push(image);
    this.updatePendingImagePreview();
    this.appendSystemMessage("Screenshot captured. It will be sent with your next message.");
  }
  async handleScreenshotAction() {
    this.appendSystemMessage("Kimi requested a screenshot. Capturing now...");
    const image = await this.captureScreen();
    if (!image) {
      this.appendSystemMessage("Failed to capture screenshot.");
      this.setProcessing(false);
      return;
    }
    this.appendSystemMessage("Screenshot captured and sent back to Kimi.");
    this.setProcessing(true);
    this.updateStatus("prompting");
    const activeCanvas = this.getActiveCanvasFile();
    let canvasData;
    if (activeCanvas) {
      canvasData = await this.plugin.canvasManager.readCanvas(activeCanvas);
    }
    const system = this.buildSystemPrompt(canvasData, activeCanvas?.path, true);
    const promptText = `${system}

--- User Request ---
Here is the screenshot of the current canvas. Please analyze the visual layout and suggest improvements. If needed, output a canvas operation block.`;
    this.plugin.kimi.sendPrompt(promptText, [image]);
  }
  async captureScreen() {
    const { screenshotMode } = this.plugin.settings;
    const tmpPath = `${this.plugin.getVaultPath()}/.obsidian/plugins/obsidian-kimi-canvas/.tmp-screenshot.png`;
    let args = [];
    if (screenshotMode === "full") {
      args = ["-x", tmpPath];
    } else if (screenshotMode === "window") {
      args = ["-w", tmpPath];
    } else {
      args = ["-i", tmpPath];
    }
    try {
      await new Promise((resolve, reject) => {
        const { execFile } = require("child_process");
        execFile("screencapture", args, (err) => {
          if (err)
            reject(err);
          else
            resolve();
        });
      });
      const data = await this.app.vault.adapter.readBinary(tmpPath);
      const base64 = this.arrayBufferToBase64(data);
      return { mimeType: "image/png", data: base64 };
    } catch (e) {
      console.error("Screenshot failed:", e);
      return null;
    }
  }
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  getActiveCanvasFile() {
    const file = this.app.workspace.getActiveFile();
    if (file && file.extension === "canvas")
      return file;
    let canvasFile = null;
    this.app.workspace.iterateAllLeaves((l) => {
      const f = l.view.file;
      if (f && f.extension === "canvas" && !canvasFile)
        canvasFile = f;
    });
    return canvasFile;
  }
  buildSystemPrompt(canvasData, canvasPath, hasImages = false) {
    let prompt = "You are Kimi Canvas, an AI assistant embedded in Obsidian. You help users think, organize, and visualize ideas on an infinite canvas. You can read and modify Obsidian Canvas files (JSON Canvas format).\n\n";
    if (hasImages) {
      prompt += "You are provided with screenshot(s) of the current canvas. Analyze the visual layout, spacing, alignment, color grouping, and node density. Suggest concrete layout improvements based on what you see. If you output a canvas operation block, ensure it respects the existing visual structure and fixes obvious overlaps or misalignments.\n\n";
    }
    prompt += "When the user asks you to change the canvas, you MUST reply with a human-friendly explanation first, then append a special JSON Canvas operation block at the very end of your response using this exact format:\n\n// kimi-canvas-op\n```json\n{ \"nodes\": [...], \"edges\": [...] }\n```\n\nRules for the operation block:\n1. Only include fields you want to add or update.\n2. Each node must have: id, type (text/file/link/group), x, y, width, height.\n3. For text nodes, include a 'text' field with Markdown content.\n4. For file nodes, include 'file' (path inside vault).\n5. Each edge must have: id, fromNode, toNode. Optional: fromSide, toSide, fromEnd, toEnd, label, color.\n6. If you create new nodes, generate short random alphanumeric IDs (8 chars).\n7. You do NOT need to worry about exact coordinates: the plugin will run auto-layout after applying your changes.\n\nIf you need to visually inspect the current canvas layout, output exactly `// kimi-action: screenshot`. The plugin will capture the screen and send the image back to you automatically.\n\n";
    if (canvasData && canvasPath) {
      prompt += `The current canvas file is: ${canvasPath}
Current canvas JSON:
${JSON.stringify(canvasData, null, 2)}

`;
    } else {
      prompt += "No canvas is currently open. If the user asks for canvas operations, tell them to open a .canvas file first.\n\n";
    }
    prompt += "Be concise, helpful, and creative when organizing ideas visually.";
    return prompt;
  }
  clearChat() {
    this.messages = [];
    this.messageContainer?.empty();
    this.plugin.kimi.clearSession();
    this.addWelcomeMessage();
  }
  scrollToBottom() {
    if (this.messageContainer) {
      this.messageContainer.scrollTop = this.messageContainer.scrollHeight;
    }
  }
  markdownToHtml(md) {
    return md.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>").replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/\*(.*?)\*/g, "<em>$1</em>").replace(/\n/g, "<br>");
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  kimiPath: "/Users/utadahikaru/.local/bin/kimi",
  autoLayoutOnUpdate: true,
  defaultLayoutDirection: "lr",
  screenshotMode: "window",
  autoScreenshotOnLayoutRequest: true
};
var KimiCanvasPlugin = class extends import_obsidian2.Plugin {
  settings;
  kimi;
  canvasManager;
  async onload() {
    await this.loadSettings();
    this.canvasManager = new CanvasManager(this.app.vault);
    this.kimi = new KimiBridge(this.getVaultPath(), this.settings.kimiPath);
    this.registerView(VIEW_TYPE_KIMI_CHAT, (leaf) => new KimiChatView(leaf, this));
    this.addRibbonIcon("bot", "Open Kimi Canvas chat", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-kimi-canvas-chat",
      name: "Open Kimi Canvas chat",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "kimi-auto-layout-canvas",
      name: "Auto-layout current canvas",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        const isCanvas = file?.extension === "canvas";
        if (checking)
          return isCanvas;
        if (file && isCanvas) {
          this.autoLayoutFile(file);
        }
        return true;
      }
    });
    this.addCommand({
      id: "kimi-canvas-screenshot",
      name: "Capture canvas screenshot for Kimi",
      callback: () => {
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_KIMI_CHAT);
        if (leaves.length > 0) {
          const view = leaves[0].view;
          view.triggerManualScreenshot();
        } else {
          this.activateView().then(() => {
            setTimeout(() => {
              const newLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_KIMI_CHAT);
              if (newLeaves.length > 0) {
                newLeaves[0].view.triggerManualScreenshot();
              }
            }, 500);
          });
        }
      }
    });
    this.addSettingTab(new KimiCanvasSettingTab(this.app, this));
  }
  onunload() {
    this.kimi.disconnect();
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_KIMI_CHAT);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getVaultPath() {
    const adapter = this.app.vault.adapter;
    return adapter.getBasePath ? adapter.getBasePath() : ".";
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_KIMI_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf)
        await leaf.setViewState({ type: VIEW_TYPE_KIMI_CHAT, active: true });
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  async autoLayoutFile(file) {
    const data = await this.canvasManager.readCanvas(file);
    const laidOut = this.canvasManager.autoLayout(data, {
      direction: this.settings.defaultLayoutDirection
    });
    await this.canvasManager.writeCanvas(file, laidOut);
  }
};
var KimiCanvasSettingTab = class extends import_obsidian2.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Kimi Canvas Settings" });
    new import_obsidian2.Setting(containerEl).setName("Kimi CLI path").setDesc("Path to the kimi executable. Leave as 'kimi' if it's in your system PATH.").addText(
      (text) => text.setPlaceholder("/Users/utadahikaru/.local/bin/kimi").setValue(this.plugin.settings.kimiPath).onChange(async (value) => {
        this.plugin.settings.kimiPath = value.trim() || "/Users/utadahikaru/.local/bin/kimi";
        this.plugin.kimi = new KimiBridge(this.plugin.getVaultPath(), this.plugin.settings.kimiPath);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto-layout on AI update").setDesc("Automatically re-layout the canvas after Kimi modifies it.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoLayoutOnUpdate).onChange(async (value) => {
        this.plugin.settings.autoLayoutOnUpdate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default layout direction").setDesc("Direction for auto-layout: Left-to-Right or Top-to-Bottom.").addDropdown(
      (drop) => drop.addOption("lr", "Left to Right").addOption("tb", "Top to Bottom").setValue(this.plugin.settings.defaultLayoutDirection).onChange(async (value) => {
        this.plugin.settings.defaultLayoutDirection = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Screenshot mode").setDesc("How to capture the screen when Kimi requests a screenshot or you click the camera button.").addDropdown(
      (drop) => drop.addOption("full", "Full Screen").addOption("window", "Active Window").addOption("region", "Selected Region").setValue(this.plugin.settings.screenshotMode).onChange(async (value) => {
        this.plugin.settings.screenshotMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto-respond to screenshot requests").setDesc("If enabled, the plugin will automatically capture the screen and send it back when Kimi outputs // kimi-action: screenshot.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoScreenshotOnLayoutRequest).onChange(async (value) => {
        this.plugin.settings.autoScreenshotOnLayoutRequest = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
